# Generated by Django 6.0.4 on 2026-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_street_name_seller_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='seller',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
