# Generated by Django 6.0.4 on 2026-05-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('edition', models.CharField(max_length=100)),
                ('provenance', models.TextField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='seller.seller')),
            ],
        ),
    ]
