# Generated by Django 6.0.4 on 2026-05-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_artworkimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image_url',
        ),
    ]
