# Generated by Django 6.0.4 on 2026-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_remove_artwork_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
