# Generated by Django 6.0.4 on 2026-05-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_artwork_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='listed_at',
            field=models.DateTimeField(),
        ),
    ]
