# Generated by Django 6.0.4 on 2026-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_alter_artwork_listed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
