# Generated by Django 6.0.4 on 2026-05-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='street_name',
            new_name='street_address',
        ),
    ]
